import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Swae",
      email: "ldkhini001@st.ug.edu.gh",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Mr. Kesse",
        logo: "/images/logo1.png",
        description: "best dealer",
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Mercedes Benz",
      category: "salon",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Benz",
      rating: 4,
      numReviews: 10,
      description: "Black",
    },
    {
      name: "Lexus",
      category: "salon",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Toyota",
      rating: 4.8,
      numReviews: 17,
      description: "White",
    },
    {
      name: "Land Cruiser V8",
      category: "compact",
      image: "/images/p4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Toyota",
      rating: 4.5,
      numReviews: 14,
      description: "Black",
    },
    {
      name: "Hyundai Sonata",
      category: "compact",
      image: "/images/p5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Hyundai",
      rating: 3,
      numReviews: 1,
      description: "Blue",
    },
    {
      name: "White Mercedes Benz C300",
      category: "compact",
      image: "/images/p6.jpg",
      price: 139,
      countInStock: 12,
      brand: "Benz",
      rating: 4.5,
      numReviews: 15,
      description: "White",
    },
  ],
};
export default data;
